version: '3.4'

services:
  hrleavemanagement.mvc:
    image: docker4poll/hrmanagementmvc:latest
    environment:
    - ApiUrl=https://hrleavemanagement.api
    build:
      context: .
      dockerfile: HRLeaveManagement.MVC/Dockerfile
    ports:
    - "8080:443"

  hrleavemanagement.api:
    image: docker4poll/hrmanagementapi:latest
    depends_on:
    - hrleavemanagement.mvc
    build:
      context: .
      dockerfile: HRLeaveManagement.Api/Dockerfile
    ports:
    - "5000:80"
    - "5001:443"
    environment:
     ASPNETCORE_URLS: "https://+;http://+"
     ASPNETCORE_HTTPS_PORT: "5001"
     ASPNETCORE_ENVIRONMENT: Development