# fly.toml app configuration file generated for hrmanagement on 2023-06-12T18:48:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hrmanagement"
primary_region = "lhr"

[build]
  image = "docker4poll/hrmanagementmvc:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
